version: '3.9'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
    networks:
      - default
    depends_on:
      - localdb
  localdb:
    image: mongo:6.0
    hostname: localhost
    restart: unless-stopped
    expose:
      - 27017
    networks:
      - default
networks:
  default:
    driver: bridge